import type { Scene, AspectRatio, Style, Resolution, Costume, SimpleOption } from './types';

export const VIETNAM_SCENES: Scene[] = [
  { id: 'hanoi_old_quarter', name: 'Phố Cổ Hà Nội', prompt: 'A child wearing a classic Áo Dài, exploring the charming, bustling streets of Hanoi\'s Old Quarter, with ancient houses and vibrant market stalls in the background.', imageUrl: 'https://picsum.photos/seed/hanoi/200' },
  { id: 'ha_long_bay', name: 'Vịnh Hạ Long', prompt: 'A child on a traditional wooden junk boat, sailing through the majestic limestone karsts and emerald waters of Ha Long Bay at sunrise.', imageUrl: 'https://picsum.photos/seed/halong/200' },
  { id: 'hoi_an_lanterns', name: 'Đèn Lồng Hội An', prompt: 'A child in a beautiful outfit holding a colorful lantern at night in Hoi An Ancient Town, surrounded by the warm glow of thousands of silk lanterns.', imageUrl: 'https://picsum.photos/seed/hoian/200' },
  { id: 'sapa_terraces', name: 'Ruộng Bậc Thang Sapa', prompt: 'A child dressed in local hill-tribe attire, standing amidst the stunning, green rice terraces of Sapa during the golden harvest season.', imageUrl: 'https://picsum.photos/seed/sapa/200' },
  { id: 'mekong_delta', name: 'Chợ Nổi Miền Tây', prompt: 'A child wearing a traditional conical hat on a small boat in the Mekong Delta, surrounded by boats selling colorful fruits and vegetables at a floating market.', imageUrl: 'https://picsum.photos/seed/mekong/200' },
  { id: 'hue_citadel', name: 'Kinh Thành Huế', prompt: 'A child dressed as royalty in an ancient Vietnamese imperial costume, standing inside the magnificent and historic Imperial City of Hue.', imageUrl: 'https://picsum.photos/seed/hue/200' },
  { id: 'golden_bridge', name: 'Cầu Vàng Đà Nẵng', prompt: 'A child walking on the famous Golden Bridge in Da Nang, held up by two giant stone hands, with breathtaking views of the Ba Na Hills.', imageUrl: 'https://picsum.photos/seed/danang/200' },
  { id: 'phu_quoc_beach', name: 'Biển Phú Quốc', prompt: 'A child playing joyfully on the white sandy beaches of Phu Quoc island, with a beautiful sunset over the clear turquoise water.', imageUrl: 'https://picsum.photos/seed/phuquoc/200' },
  { id: 'ninh_binh_boat', name: 'Tràng An, Ninh Bình', prompt: 'A child on a serene boat trip in Ninh Binh, gliding along a gentle river that winds through dramatic limestone cliffs and lush rice paddies.', imageUrl: 'https://picsum.photos/seed/ninhbinh/200' },
  { id: 'da_lat_flowers', name: 'Vườn Hoa Đà Lạt', prompt: 'A child surrounded by a vibrant sea of colorful flowers in a beautiful garden in Da Lat, the "City of Eternal Spring".', imageUrl: 'https://picsum.photos/seed/dalat/200' },
  { id: 'mid_autumn_festival', name: 'Tết Trung Thu', prompt: 'A child celebrating the Mid-Autumn Festival, holding a star-shaped lantern, with a lion dance performance and a bright full moon in the background.', imageUrl: 'https://picsum.photos/seed/trungthu/200' },
  { id: 'lunar_new_year', name: 'Ngày Tết Nguyên Đán', prompt: 'A child in a festive red Áo Dài for Lunar New Year (Tết), standing next to a blooming peach blossom tree and holding lucky red envelopes.', imageUrl: 'https://picsum.photos/seed/tet/200' },
  { id: 'lotus_pond', name: 'Hồ Sen Mùa Hè', prompt: 'A child gracefully posing in a traditional Vietnamese outfit by a tranquil lotus pond, with beautiful pink lotus flowers in full bloom.', imageUrl: 'https://picsum.photos/seed/lotus/200' },
  { id: 'cyclo_rider', name: 'Trên Xe Xích Lô', prompt: 'A child sitting as a passenger on a traditional cyclo, exploring a bustling, tree-lined street in a Vietnamese city like Saigon or Hanoi.', imageUrl: 'https://picsum.photos/seed/cyclo/200' },
  { id: 'water_puppet', name: 'Múa Rối Nước', prompt: 'A child watching a traditional water puppet show, with colorful wooden puppets appearing to dance on the water of a stage.', imageUrl: 'https://picsum.photos/seed/waterpuppet/200' },
  { id: 'mui_ne_sund_dunes', name: 'Đồi Cát Mũi Né', prompt: 'A child sliding down the beautiful red and white sand dunes of Mui Ne, with a clear blue sky above.', imageUrl: 'https://picsum.photos/seed/muine/200' },
  { id: 'ban_gioc_waterfall', name: 'Thác Bản Giốc', prompt: 'A child standing in awe before the magnificent Ban Gioc Waterfall, the largest waterfall in Vietnam, on the border with China.', imageUrl: 'https://picsum.photos/seed/bangioc/200' },
  { id: 'phong_nha_cave', name: 'Hang Động Phong Nha', prompt: 'A child on a boat inside the mystical Phong Nha-Ke Bang cave, surrounded by spectacular stalactites and stalagmites.', imageUrl: 'https://picsum.photos/seed/phongnha/200' },
  { id: 'con_dao_islands', name: 'Biển Côn Đảo', prompt: 'A child on a pristine, secluded beach in the Con Dao islands, with crystal-clear water and lush green hills in the background.', imageUrl: 'https://picsum.photos/seed/condao/200' },
  { id: 'my_son_sanctuary', name: 'Thánh Địa Mỹ Sơn', prompt: 'A child exploring the ancient, mysterious Hindu temples of the My Son Sanctuary, a UNESCO World Heritage site.', imageUrl: 'https://picsum.photos/seed/myson/200' },
  { id: 'ha_giang_loop', name: 'Cung Đường Hà Giang', prompt: 'A child looking out at the breathtaking mountain passes and winding roads of the Ha Giang Loop in Northern Vietnam.', imageUrl: 'https://picsum.photos/seed/hagiang/200' },
  { id: 'ba_be_lake', name: 'Hồ Ba Bể', prompt: 'A child peacefully rowing a dugout canoe on the tranquil, emerald waters of Ba Be Lake, surrounded by limestone mountains.', imageUrl: 'https://picsum.photos/seed/babe/200' },
  { id: 'hoan_kiem_lake', name: 'Hồ Gươm, Hà Nội', prompt: 'A child standing on the iconic red Huc Bridge leading to the Ngoc Son Temple on Hoan Kiem Lake in the heart of Hanoi.', imageUrl: 'https://picsum.photos/seed/hoankiem/200' },
  { id: 'marble_mountains', name: 'Ngũ Hành Sơn, Đà Nẵng', prompt: 'A child climbing the steps of the Marble Mountains in Da Nang, with panoramic views of the city and coastline.', imageUrl: 'https://picsum.photos/seed/marblemountain/200' },
  { id: 'independence_palace', name: 'Dinh Độc Lập', prompt: 'A child standing in front of the historic Independence Palace (Reunification Palace) in Ho Chi Minh City.', imageUrl: 'https://picsum.photos/seed/reunification/200' },
  { id: 'temple_of_literature', name: 'Văn Miếu Quốc Tử Giám', prompt: 'A child dressed as a young scholar at the Temple of Literature in Hanoi, Vietnam\'s first university.', imageUrl: 'https://picsum.photos/seed/vanmieu/200' },
  { id: 'cuc_phuong_national_park', name: 'Rừng Quốc Gia Cúc Phương', prompt: 'A child discovering the lush greenery and ancient trees of Cuc Phuong National Park, the oldest national park in Vietnam.', imageUrl: 'https://picsum.photos/seed/cucphuong/200' },
  { id: 'ca_mau_cape', name: 'Mũi Cà Mau', prompt: 'A child at Ca Mau Cape, the southernmost point of mainland Vietnam, with a landmark showing the national coordinates.', imageUrl: 'https://picsum.photos/seed/camau/200' },
  { id: 'linh_phuoc_pagoda', name: 'Chùa Linh Phước, Đà Lạt', prompt: 'A child amazed by the intricate mosaic designs made from glass and pottery shards at the Linh Phuoc Pagoda in Da Lat.', imageUrl: 'https://picsum.photos/seed/linhphuoc/200' },
  { id: 'mu_cang_chai', name: 'Mù Cang Chải, Yên Bái', prompt: 'A child amidst the stunning "golden rice sea" of the terraced fields in Mu Cang Chai during the harvest season.', imageUrl: 'https://picsum.photos/seed/mucangchai/200' },
];

export const WORLD_SCENES: Scene[] = [
    { id: 'paris_eiffel_tower', name: 'Tháp Eiffel, Paris', prompt: 'A child in a chic Parisian outfit with a beret, standing on a charming street with the iconic Eiffel Tower in the background.', imageUrl: 'https://picsum.photos/seed/paris/200' },
    { id: 'egypt_pyramids', name: 'Kim Tự Tháp, Ai Cập', prompt: 'A child dressed as a little explorer, riding a camel with the Great Pyramids of Giza and the Sphinx in the warm desert light.', imageUrl: 'https://picsum.photos/seed/egypt/200' },
    { id: 'santorini_greece', name: 'Santorini, Hy Lạp', prompt: 'A child standing amidst the famous blue-domed white houses of Santorini, overlooking the sparkling Aegean Sea.', imageUrl: 'https://picsum.photos/seed/santorini/200' },
    { id: 'kyoto_cherry_blossoms', name: 'Hoa Anh Đào Kyoto, Nhật Bản', prompt: 'A child wearing a beautiful kimono under a canopy of blooming cherry blossom trees in a serene, traditional Japanese garden in Kyoto.', imageUrl: 'https://picsum.photos/seed/kyoto/200' },
    { id: 'venice_canals', name: 'Kênh Đào Venice, Ý', prompt: 'A child enjoying a ride on a classic gondola through the picturesque canals of Venice, surrounded by historic Italian architecture.', imageUrl: 'https://picsum.photos/seed/venice/200' },
    { id: 'new_york_times_square', name: 'Quảng Trường Thời Đại, New York', prompt: 'A child looking up in wonder at the dazzling, vibrant neon billboards and bustling energy of Times Square at night.', imageUrl: 'https://picsum.photos/seed/timessquare/200' },
    { id: 'machu_picchu_peru', name: 'Machu Picchu, Peru', prompt: 'A child in colorful traditional Peruvian clothing, gazing out over the ancient, breathtaking Incan citadel of Machu Picchu.', imageUrl: 'https://picsum.photos/seed/machupicchu/200' },
    { id: 'african_safari', name: 'Thảo Nguyên Châu Phi', prompt: 'A child in safari gear, safely observing majestic wildlife like elephants and giraffes on the African savanna against a stunning sunset.', imageUrl: 'https://picsum.photos/seed/safari/200' },
    { id: 'swiss_alps', name: 'Dãy Alps, Thụy Sĩ', prompt: 'A warmly dressed child playing joyfully in the pristine snow, with the magnificent snow-capped Swiss Alps under a clear blue sky.', imageUrl: 'https://picsum.photos/seed/alps/200' },
    { id: 'great_wall_of_china', name: 'Vạn Lý Trường Thành, Trung Quốc', prompt: 'A child walking along a scenic, majestic section of the Great Wall of China, with rolling green hills in the distance.', imageUrl: 'https://picsum.photos/seed/greatwall/200' },
    { id: 'rome_colosseum', name: 'Đấu Trường La Mã, Ý', prompt: 'A child dressed as a little Roman citizen, standing in front of the ancient and awe-inspiring Colosseum in Rome.', imageUrl: 'https://picsum.photos/seed/rome/200' },
    { id: 'holland_tulip_fields', name: 'Cánh Đồng Tulip, Hà Lan', prompt: 'A child in a vast, vibrant field of colorful tulips in the Netherlands, with a classic Dutch windmill in the background.', imageUrl: 'https://picsum.photos/seed/tulips/200' },
    { id: 'hollywood_los_angeles', name: 'Hollywood, Mỹ', prompt: 'A child posing like a movie star on the Hollywood Walk of Fame, with the famous Hollywood sign visible in the hills behind.', imageUrl: 'https://picsum.photos/seed/hollywoodla/200' },
    { id: 'grand_canyon_usa', name: 'Hẻm Núi Grand Canyon, Mỹ', prompt: 'A child looking out at the breathtaking, expansive vista of the Grand Canyon during a spectacular sunrise or sunset.', imageUrl: 'https://picsum.photos/seed/grandcanyon/200' },
    { id: 'rio_christ_the_redeemer', name: 'Tượng Chúa Cứu Thế, Brazil', prompt: 'A child looking out over the stunning cityscape of Rio de Janeiro and Sugarloaf Mountain from the base of the Christ the Redeemer statue.', imageUrl: 'https://picsum.photos/seed/rio/200' },
    { id: 'london_big_ben', name: 'Tháp Big Ben, London', prompt: 'A child dressed in a classic British outfit, like a peacoat, standing near the River Thames with the Big Ben clock tower and Houses of Parliament in London.', imageUrl: 'https://picsum.photos/seed/london/200' },
    { id: 'moscow_red_square', name: 'Quảng Trường Đỏ, Moscow', prompt: 'A child in a warm, traditional Russian coat and ushanka hat, with the colorful onion domes of St. Basil\'s Cathedral in Moscow\'s Red Square behind them.', imageUrl: 'https://picsum.photos/seed/moscow/200' },
    { id: 'neuschwanstein_castle', name: 'Lâu Đài Neuschwanstein, Đức', prompt: 'A child dressed as a fairytale prince or princess, looking at the magical Neuschwanstein Castle perched in the Bavarian Alps of Germany.', imageUrl: 'https://picsum.photos/seed/neuschwanstein/200' },
    { id: 'tuscany_hills', name: 'Đồi Tuscany, Ý', prompt: 'A child wandering through the idyllic rolling hills of Tuscany, Italy, with cypress trees, golden fields, and a rustic farmhouse in the distance.', imageUrl: 'https://picsum.photos/seed/tuscany/200' },
    { id: 'prague_charles_bridge', name: 'Cầu Charles, Praha', prompt: 'A child watching artists on the historic Charles Bridge in Prague at dawn, with Prague Castle visible across the Vltava River.', imageUrl: 'https://picsum.photos/seed/prague/200' },
    { id: 'barcelona_gaudi', name: 'Kiến Trúc Gaudi, Barcelona', prompt: 'A child marveling at the unique, colorful mosaic architecture of Antoni Gaudí in Park Güell, Barcelona, Spain.', imageUrl: 'https://picsum.photos/seed/barcelona/200' },
    { id: 'scottish_highlands', name: 'Cao Nguyên Scotland', prompt: 'A child in a tartan plaid scarf, looking out over a dramatic, misty loch in the Scottish Highlands, with ancient castle ruins nearby.', imageUrl: 'https://picsum.photos/seed/scotland/200' },
    { id: 'amsterdam_canals', name: 'Kênh Đào Amsterdam, Hà Lan', prompt: 'A child standing on a picturesque bridge over a canal in Amsterdam, with classic narrow Dutch houses and bicycles lined up.', imageUrl: 'https://picsum.photos/seed/amsterdam/200' },
    { id: 'taj_mahal_india', name: 'Đền Taj Mahal, Ấn Độ', prompt: 'A child in elegant, traditional Indian attire, standing by the reflecting pool in front of the magnificent Taj Mahal at sunrise.', imageUrl: 'https://picsum.photos/seed/tajmahal/200' },
    { id: 'angkor_wat_cambodia', name: 'Đền Angkor Wat, Campuchia', prompt: 'A child dressed as a little explorer, surrounded by the ancient, vine-covered temple ruins of Angkor Wat in Cambodia.', imageUrl: 'https://picsum.photos/seed/angkorwat/200' },
    { id: 'bali_indonesia', name: 'Cổng Trời Bali, Indonesia', prompt: 'A child standing between the iconic "Gates of Heaven" at Lempuyang Temple in Bali, with a stunning view of Mount Agung.', imageUrl: 'https://picsum.photos/seed/bali/200' },
    { id: 'seoul_palace', name: 'Cung Điện Seoul, Hàn Quốc', prompt: 'A child wearing a colorful traditional Hanbok at the majestic Gyeongbokgung Palace in Seoul, with modern city skyscrapers in the background.', imageUrl: 'https://picsum.photos/seed/seoul/200' },
    { id: 'bangkok_temples', name: 'Chùa Vàng Bangkok, Thái Lan', prompt: 'A child standing respectfully before the glittering, ornate golden temples of the Grand Palace in Bangkok, Thailand.', imageUrl: 'https://picsum.photos/seed/bangkok/200' },
    { id: 'singapore_gardens', name: 'Vườn Bên Vịnh, Singapore', prompt: 'A child looking up at the futuristic, illuminated Supertree Grove in Singapore\'s Gardens by the Bay at night.', imageUrl: 'https://picsum.photos/seed/singapore/200' },
    { id: 'dubai_cityscape', name: 'Thành Phố Dubai', prompt: 'A child gazing at the ultra-modern, towering skyline of Dubai from a high vantage point, with the Burj Khalifa prominent.', imageUrl: 'https://picsum.photos/seed/dubai/200' },
];

export const STUDIO_SCENES: Scene[] = [
  { id: 'minimalist_studio', name: 'Studio Tối Giản', prompt: 'A professional studio portrait of the child against a clean, minimalist background (white, grey, or pastel), focusing on their natural expression.', imageUrl: 'https://picsum.photos/seed/minimalist/200' },
  { id: 'vintage_studio', name: 'Studio Cổ Điển', prompt: 'A nostalgic, vintage-themed studio portrait of the child, with classic props like an old telephone, a stack of books, or a vintage suitcase.', imageUrl: 'https://picsum.photos/seed/vintage/200' },
  { id: 'magical_forest_studio', name: 'Studio Khu Rừng Phép Thuật', prompt: 'An enchanting studio setup that looks like a magical forest, with fairy lights, mossy logs, and glowing mushrooms surrounding the child.', imageUrl: 'https://picsum.photos/seed/magicforest/200' },
  { id: 'royal_studio', name: 'Studio Hoàng Gia', prompt: 'A regal studio portrait of the child as a prince or princess, sitting on an elegant, small throne with a luxurious velvet curtain backdrop.', imageUrl: 'https://picsum.photos/seed/royal/200' },
  { id: 'cozy_library_studio', name: 'Studio Thư Viện', prompt: 'A warm and cozy studio setting designed like a library, with the child sitting on a comfortable armchair surrounded by floor-to-ceiling bookshelves.', imageUrl: 'https://picsum.photos/seed/library/200' },
  { id: 'chef_studio', name: 'Studio Đầu Bếp', prompt: 'A fun studio portrait of the child as a little chef, wearing a chef\'s hat and apron in a bright, modern kitchen set, playfully tossing flour.', imageUrl: 'https://picsum.photos/seed/chefstudio/200' },
  { id: 'astronaut_studio', name: 'Studio Phi Hành Gia', prompt: 'A futuristic studio portrait of the child in an astronaut costume, with a backdrop of planets, stars, and galaxies.', imageUrl: 'https://picsum.photos/seed/astronautstudio/200' },
  { id: 'superhero_studio', name: 'Studio Siêu Anh Hùng', prompt: 'A dynamic studio portrait of the child as a superhero, posing in front of a dramatic cityscape backdrop with a spotlight effect.', imageUrl: 'https://picsum.photos/seed/superherostudio/200' },
  { id: 'garden_studio', name: 'Studio Vườn Hoa', prompt: 'A beautiful studio portrait with the child surrounded by an abundance of realistic, high-quality artificial flowers and greenery, creating a garden oasis.', imageUrl: 'https://picsum.photos/seed/gardenstudio/200' },
  { id: 'bohemian_studio', name: 'Studio Bohemian', prompt: 'A chic, bohemian-style studio portrait with the child sitting on a rattan chair, surrounded by macrame wall hangings, pampas grass, and plants.', imageUrl: 'https://picsum.photos/seed/bohemian/200' },
  { id: 'artist_loft_studio', name: 'Studio Họa Sĩ', prompt: 'A creative studio portrait of the child as a little artist in a loft-style setting, holding a paintbrush and standing by an easel with a colorful canvas.', imageUrl: 'https://picsum.photos/seed/artiststudio/200' },
  { id: 'rockstar_studio', name: 'Studio Ngôi Sao Nhạc Rock', prompt: 'An energetic studio portrait of the child as a rockstar, holding a toy electric guitar on a stage set with spotlights and amplifiers.', imageUrl: 'https://picsum.photos/seed/rockstarstudio/200' },
  { id: 'pilot_studio', name: 'Studio Phi Công', prompt: 'A professional studio portrait of the child as a pilot, sitting in a mock airplane cockpit with various controls and a sky view backdrop.', imageUrl: 'https://picsum.photos/seed/pilotstudio/200' },
  { id: 'camping_studio', name: 'Studio Cắm Trại', prompt: 'A cozy studio setup that mimics a camping scene at night, with a tent, a faux campfire, and a starry night sky backdrop.', imageUrl: 'https://picsum.photos/seed/camping/200' },
  { id: 'beach_studio', name: 'Studio Bãi Biển', prompt: 'A bright and airy studio portrait mimicking a day at the beach, with real sand, seashells, a beach chair, and a beautiful ocean backdrop.', imageUrl: 'https://picsum.photos/seed/beachstudio/200' },
];

export const ACCESSORY_SCENES: Scene[] = [
    { id: 'sunflowers', name: 'Hoa Hướng Dương', prompt: 'A joyful child holding a large, bright bouquet of sunflowers in a sunny field.', imageUrl: 'https://picsum.photos/seed/sunflowers/200' },
    { id: 'balloons', name: 'Bong Bóng Bay', prompt: 'A child holding a big bunch of colorful helium balloons, looking up at them with wonder.', imageUrl: 'https://picsum.photos/seed/balloons/200' },
    { id: 'teddy_bear', name: 'Gấu Bông Teddy', prompt: 'A sweet portrait of a child hugging a classic, fluffy teddy bear in a cozy, soft-lit room.', imageUrl: 'https://picsum.photos/seed/teddybear/200' },
    { id: 'princess_crown', name: 'Vương Miện Công Chúa', prompt: 'A child wearing a sparkling, elegant princess crown, with a magical, glowing background.', imageUrl: 'https://picsum.photos/seed/crown/200' },
    { id: 'magic_wand', name: 'Đũa Phép Thuật', prompt: 'A child holding a glowing magic wand, with shimmering sparkles and trails of light swirling around.', imageUrl: 'https://picsum.photos/seed/magicwand/200' },
    { id: 'superhero_cape', name: 'Áo Choàng Siêu Anh Hùng', prompt: 'A child wearing a flowing superhero cape, standing in a powerful pose in front of a cityscape.', imageUrl: 'https://picsum.photos/seed/superherocape/200' },
    { id: 'giant_lollipop', name: 'Kẹo Mút Khổng Lồ', prompt: 'A fun photo of a child holding a giant, colorful swirl lollipop, with a cheerful expression.', imageUrl: 'https://picsum.photos/seed/lollipop/200' },
    { id: 'small_guitar', name: 'Đàn Ghita Nhỏ', prompt: 'A child sitting on a stool and strumming a small acoustic guitar, like a little musician.', imageUrl: 'https://picsum.photos/seed/guitar/200' },
    { id: 'mystery_box', name: 'Hộp Quà Bí Ẩn', prompt: 'A child peeking into a beautifully wrapped gift box that is glowing from the inside.', imageUrl: 'https://picsum.photos/seed/giftbox/200' },
    { id: 'fairy_tale_book', name: 'Sách Cổ Tích', prompt: 'A child sitting comfortably, engrossed in reading a large, beautifully illustrated fairy tale book.', imageUrl: 'https://picsum.photos/seed/storybook/200' },
    { id: 'soap_bubbles', name: 'Bong Bóng Xà Phòng', prompt: 'A child blowing soap bubbles, with iridescent bubbles floating all around them in the sunlight.', imageUrl: 'https://picsum.photos/seed/bubbles/200' },
    { id: 'toy_car', name: 'Xe Hơi Đồ Chơi', prompt: 'A child sitting in a cool, ride-on toy car, pretending to drive.', imageUrl: 'https://picsum.photos/seed/toycar/200' },
    { id: 'barbie_doll', name: 'Búp Bê Barbie', prompt: 'A glamorous portrait of a child posing with their favorite Barbie doll, both dressed in matching stylish outfits.', imageUrl: 'https://picsum.photos/seed/barbie/200' },
    { id: 'lego_creation', name: 'Sáng Tạo LEGO', prompt: 'A child proudly showing off an amazing creation they built with colorful LEGO bricks.', imageUrl: 'https://picsum.photos/seed/lego/200' },
    { id: 'rose_petal_shower', name: 'Mưa Cánh Hoa Hồng', prompt: 'A beautiful shot of a child with rose petals gently falling around them.', imageUrl: 'https://picsum.photos/seed/rosepetals/200' },
];

export const AO_DAI_COSTUMES: Costume[] = [
  { id: 'ao_dai_lua_to_tam_truyen_thong', name: 'Áo Dài Lụa Tơ Tằm Truyền Thống', prompt: 'A traditional Vietnamese Áo Dài made from luxurious, flowing silk, simple yet profoundly elegant in a soft pastel color.', imageUrl: 'https://picsum.photos/seed/aodaitruyenthong/200' },
  { id: 'ao_dai_do_ngay_tet', name: 'Áo Dài Đỏ Ngày Tết', prompt: 'A vibrant, festive red Áo Dài, often decorated with gold embroidery of apricot blossoms or phoenixes, perfect for the Lunar New Year.', imageUrl: 'https://picsum.photos/seed/aodaitet/200' },
  { id: 'ao_dai_trang_nu_sinh', name: 'Áo Dài Trắng Nữ Sinh', prompt: 'The iconic, pure white Áo Dài of a Vietnamese high school girl, symbolizing innocence and grace, simple and unadorned.', imageUrl: 'https://picsum.photos/seed/aodainusinh/200' },
  { id: 'ao_dai_theu_hoa_sen', name: 'Áo Dài Thêu Hoa Sen', prompt: 'An elegant Áo Dài featuring exquisite hand-embroidery of lotus flowers and leaves, Vietnam\'s national flower.', imageUrl: 'https://picsum.photos/seed/aodailotus/200' },
  { id: 'ao_dai_gam_co_dien', name: 'Áo Dài Gấm Cổ Điển', prompt: 'A classic Áo Dài made from traditional brocade fabric (gấm), with intricate woven patterns, exuding a sense of royalty and nostalgia.', imageUrl: 'https://picsum.photos/seed/aodaigam/200' },
  { id: 'ao_dai_cach_tan_hien_dai', name: 'Áo Dài Cách Tân Hiện Đại', prompt: 'A modern, stylized Áo Dài with a shorter length (knee-length), often worn with culottes or jeans, featuring bold prints or contemporary cuts.', imageUrl: 'https://picsum.photos/seed/aodaicachtan/200' },
  { id: 'ao_dai_ve_tay_nghe_thuat', name: 'Áo Dài Vẽ Tay Nghệ Thuật', prompt: 'A unique Áo Dài that serves as a canvas for a beautiful, hand-painted artwork, such as a landscape, flowers, or abstract design.', imageUrl: 'https://picsum.photos/seed/aodaipainted/200' },
  { id: 'ao_dai_co_yem', name: 'Áo Dài Cổ Yếm', prompt: 'A graceful and slightly more traditional style of Áo Dài that incorporates an ancient halter-top (yếm) design at the collar.', imageUrl: 'https://picsum.photos/seed/aodaiyem/200' },
  { id: 'ao_dai_phoi_ren_tinh_te', name: 'Áo Dài Phối Ren Tinh Tế', prompt: 'A romantic Áo Dài featuring delicate lace overlays on the sleeves, collar, or parts of the tunic, adding a touch of modern femininity.', imageUrl: 'https://picsum.photos/seed/aodailace/200' },
  { id: 'ao_dai_co_dau', name: 'Áo Dài Cô Dâu', prompt: 'An ornate and luxurious red or white Áo Dài for a bride, heavily decorated with embroidery, beads, and often paired with a matching Khăn Đống headdress.', imageUrl: 'https://picsum.photos/seed/aodaibride/200' },
  { id: 'ao_dai_nhung_sang_trong', name: 'Áo Dài Nhung Sang Trọng', prompt: 'A rich and luxurious Áo Dài made from deep-colored velvet, perfect for formal evening events, exuding sophistication.', imageUrl: 'https://picsum.photos/seed/aodaivelvet/200' },
  { id: 'ao_dai_in_hoa_tiet_hinh_hoc', name: 'Áo Dài In Họa Tiết Hình Học', prompt: 'A contemporary Áo Dài with bold, geometric patterns and a modern color palette, blending tradition with graphic design.', imageUrl: 'https://picsum.photos/seed/aodaigeometric/200' },
  { id: 'ao_dai_tim_xu_hue', name: 'Áo Dài Tím Xứ Huế', prompt: 'A dreamy and poetic Áo Dài in a signature shade of Hue purple, known for its romantic and gentle beauty.', imageUrl: 'https://picsum.photos/seed/aodaihue/200' },
  { id: 'ao_dai_dinh_cuom_da_quy', name: 'Áo Dài Đính Cườm Đá Quý', prompt: 'A glamorous Áo Dài meticulously hand-beaded with sparkling crystals, sequins, and gemstones, creating a dazzling effect.', imageUrl: 'https://picsum.photos/seed/aodaibeaded/200' },
  { id: 'ao_dai_vai_taffeta', name: 'Áo Dài Vải Taffeta', prompt: 'A structured and modern Áo Dài made from crisp taffeta fabric, which gives it a sculptural and high-fashion silhouette.', imageUrl: 'https://picsum.photos/seed/aodaitaffeta/200' },
  { id: 'ao_dai_theu_chim_phuong', name: 'Áo Dài Thêu Chim Phượng', prompt: 'A regal Áo Dài adorned with a majestic embroidered phoenix, a symbol of beauty, grace, and good fortune.', imageUrl: 'https://picsum.photos/seed/aodaiphoenix/200' },
  { id: 'ao_dai_co_thuyen', name: 'Áo Dài Cổ Thuyền', prompt: 'A stylish Áo Dài with a boat neck collar, offering a modern and elegant twist to the traditional high collar.', imageUrl: 'https://picsum.photos/seed/aodaiboatneck/200' },
  { id: 'ao_dai_tay_phong', name: 'Áo Dài Tay Phồng', prompt: 'A fashionable, modern take on the Áo Dài featuring voluminous puff sleeves, blending classic lines with a contemporary trend.', imageUrl: 'https://picsum.photos/seed/aodaipuffsleeve/200' },
  { id: 'ao_dai_in_tranh_dong_ho', name: 'Áo Dài In Tranh Đông Hồ', prompt: 'A culturally rich Áo Dài printed with motifs from traditional Vietnamese Đông Hồ folk paintings.', imageUrl: 'https://picsum.photos/seed/aodaidongho/200' },
  { id: 'ao_dai_den_huyen_bi', name: 'Áo Dài Đen Huyền Bí', prompt: 'A chic and mysterious all-black Áo Dài, often made from silk or velvet, offering a powerful and sophisticated modern look.', imageUrl: 'https://picsum.photos/seed/aodaiblack/200' },
];

export const LUXURY_COSTUMES: Costume[] = [
  { id: 'gucci_tweed_suit', name: 'Bộ Suit Vải Tweed Gucci', prompt: 'A bespoke, flawlessly tailored Gucci-style tweed suit with elegant gold buttons and silk lining.', imageUrl: 'https://picsum.photos/seed/guccisuit/200' },
  { id: 'dior_ball_gown', name: 'Váy Dạ Hội Dior', prompt: 'An ethereal Christian Dior-inspired haute couture ball gown made of layers of soft tulle, adorned with delicate embroidery.', imageUrl: 'https://picsum.photos/seed/diorgown/200' },
  { id: 'burberry_trench_coat', name: 'Áo Măng Tô Burberry', prompt: 'A classic, miniature Burberry trench coat, perfectly styled for a child, exuding timeless British elegance.', imageUrl: 'https://picsum.photos/seed/burberry/200' },
  { id: 'versace_silk_robe', name: 'Áo Choàng Lụa Versace', prompt: 'A luxurious Versace-style silk robe featuring the iconic Barocco print in gold and black.', imageUrl: 'https://picsum.photos/seed/versace/200' },
  { id: 'chanel_boucle_jacket', name: 'Áo Khoác Vải Bouclé Chanel', prompt: 'A chic Chanel-inspired bouclé jacket with pearl detailing, paired with a matching skirt.', imageUrl: 'https://picsum.photos/seed/chanel/200' },
  { id: 'balenciaga_couture', name: 'Váy Couture Balenciaga', prompt: 'A dramatic, architectural Balenciaga-inspired haute couture gown with a voluminous silhouette.', imageUrl: 'https://picsum.photos/seed/balenciaga/200' },
  { id: 'armani_velvet_tuxedo', name: 'Tuxedo Nhung Armani', prompt: 'A sharp, custom-fit Armani-style velvet tuxedo in a deep jewel tone, with a satin lapel.', imageUrl: 'https://picsum.photos/seed/armani/200' },
  { id: 'valentino_red_dress', name: 'Váy Đỏ Valentino', prompt: 'A stunning, signature Valentino red dress with elegant ruffles and a flowing design.', imageUrl: 'https://picsum.photos/seed/valentino/200' },
  { id: 'royal_prince_attire', name: 'Trang Phục Hoàng Tử', prompt: 'The regal attire of a young prince, complete with a velvet tunic, gold epaulets, and a small, elegant crown.', imageUrl: 'https://picsum.photos/seed/prince/200' },
  { id: 'celestial_goddess_dress', name: 'Váy Nữ Thần Thiên Hà', prompt: 'A celestial goddess dress that seems woven from the night sky, studded with tiny, glowing stars and a flowing, galaxy-print train.', imageUrl: 'https://picsum.photos/seed/goddess/200' },
  { id: 'steampunk_adventurer', name: 'Nhà Thám Hiểm Steampunk', prompt: 'A sophisticated Steampunk adventurer outfit with brass goggles, a leather vest with gear details, and a top hat.', imageUrl: 'https://picsum.photos/seed/steampunk/200' },
  { id: 'futuristic_techwear', name: 'Đồ Công Nghệ Tương Lai', prompt: 'A sleek, futuristic techwear outfit with holographic panels, LED light strips, and a minimalist, aerodynamic design.', imageUrl: 'https://picsum.photos/seed/techwear/200' },
  { id: 'oscar_gala_tux', name: 'Tuxedo Dạ Hội Oscar', prompt: 'A miniature tuxedo worthy of the Oscar gala, perfectly tailored with a classic bow tie and shiny patent leather shoes.', imageUrl: 'https://picsum.photos/seed/oscartux/200' },
  { id: 'met_gala_avant_garde', name: 'Trang Phục Met Gala', prompt: 'An avant-garde, artistic ensemble inspired by the Met Gala, featuring unusual shapes, materials, and a high-fashion concept.', imageUrl: 'https://picsum.photos/seed/metgala/200' },
  { id: 'venetian_masquerade', name: 'Lễ Hội Hóa Trang Venice', prompt: 'An opulent Venetian masquerade ball costume, with a velvet gown or suit, and an ornate, feather-adorned mask.', imageUrl: 'https://picsum.photos/seed/venetian/200' },
  { id: 'hollywood_golden_age', name: 'Minh Tinh Hollywood', prompt: 'A glamorous outfit from the Golden Age of Hollywood, like a shimmering floor-length gown with a faux fur stole.', imageUrl: 'https://picsum.photos/seed/hollywood/200' },
  { id: 'Equestrian_champion', name: 'Vận Động Viên Đua Ngựa', prompt: 'A polished equestrian champion\'s outfit, including a riding jacket, crisp white jodhpurs, and tall leather boots.', imageUrl: 'https://picsum.photos/seed/equestrian/200' },
  { id: 'yacht_captain', name: 'Thuyền Trưởng Du Thuyền', prompt: 'The smart, crisp white uniform of a luxury yacht captain, with a captain\'s hat and gold accents.', imageUrl: 'https://picsum.photos/seed/yacht/200' },
  { id: 'vogue_cover_model', name: 'Người Mẫu Bìa Vogue', prompt: 'A high-fashion, editorial-style outfit suitable for a Vogue magazine cover, showcasing a bold and trendy design.', imageUrl: 'https://picsum.photos/seed/vogue/200' },
  { id: 'luxe_cashmere_set', name: 'Bộ Đồ Cashmere Cao Cấp', prompt: 'An incredibly soft and luxurious matching cashmere lounge set in a neutral cream or grey color.', imageUrl: 'https://picsum.photos/seed/cashmere/200' },
];

export const VIETNAM_REGIONAL_COSTUMES: Costume[] = [
  { id: 'hmong_traditional', name: 'Dân Tộc H\'Mông', prompt: 'A traditional H\'Mong outfit with a vibrant, intricately embroidered pleated skirt, a dark indigo top, and elaborate silver jewelry.', imageUrl: 'https://picsum.photos/seed/hmong/200' },
  { id: 'ao_dai_khan_dong', name: 'Áo Dài Khăn Đống', prompt: 'A classic Vietnamese Áo Dài, paired with a traditional circular headdress (Khăn Đống) for formal occasions.', imageUrl: 'https://picsum.photos/seed/aodaikhandong/200' },
  { id: 'ao_ba_ba', name: 'Áo Bà Ba Miền Tây', prompt: 'A simple and charming Southern Vietnamese silk pajama-style outfit (Áo Bà Ba), often worn with a checkered scarf (khăn rằn) and a conical hat.', imageUrl: 'https://picsum.photos/seed/aobaba/200' },
  { id: 'cham_dancer', name: 'Vũ Công Chăm Pa', prompt: 'The regal and ornate attire of a traditional Chăm dancer, featuring a tall, pointed crown, rich silk garments, and golden accessories.', imageUrl: 'https://picsum.photos/seed/cham/200' },
  { id: 'tay_nguyen_gong', name: 'Lễ Hội Cồng Chiêng', prompt: 'The ceremonial dress of a person from the Central Highlands (Tây Nguyên), featuring woven loincloths or skirts with bold geometric patterns.', imageUrl: 'https://picsum.photos/seed/taynguyen/200' },
  { id: 'nhat_binh_royal', name: 'Áo Nhật Bình', prompt: 'A Nguyễn Dynasty royal costume (Áo Nhật Bình), a formal, wide-sleeved robe with intricate patterns of phoenixes and flowers.', imageUrl: 'https://picsum.photos/seed/nhatbinh/200' },
  { id: 'red_dao_headdress', name: 'Dân Tộc Dao Đỏ', prompt: 'The striking traditional costume of the Red Dao people, distinguished by a large, elaborate red headdress and indigo clothing adorned with red tassels.', imageUrl: 'https://picsum.photos/seed/reddao/200' },
  { id: 'thai_ethnic_blouse', name: 'Dân Tộc Thái', prompt: 'The traditional attire of the Thái ethnic group, featuring a distinctive tight-fitting colored blouse (áo cóm) with a row of silver butterfly-shaped buttons.', imageUrl: 'https://picsum.photos/seed/thaigroup/200' },
  { id: 'muong_ethnic_skirt', name: 'Dân Tộc Mường', prompt: 'The costume of the Mường ethnic group, known for its long, black skirt with a beautifully woven waistband showcasing complex patterns.', imageUrl: 'https://picsum.photos/seed/muong/200' },
  { id: 'ninh_thuan_pottery_maker', name: 'Làng Gốm Bàu Trúc', prompt: 'The simple, traditional working clothes of a Chăm artisan from the Bàu Trúc pottery village in Ninh Thuận.', imageUrl: 'https://picsum.photos/seed/bautruc/200' },
  { id: 'ao_tu_than', name: 'Áo Tứ Thân', prompt: 'The "four-part dress" (Áo Tứ Thân) of Northern Vietnamese women, consisting of a long tunic split into four flaps, worn with a long skirt and a sash.', imageUrl: 'https://picsum.photos/seed/aotuthan/200' },
  { id: 'kinh_scholar', name: 'Trang Phục Nho Sĩ', prompt: 'The modest, dignified robes of an ancient Kinh scholar (Nho Sĩ), typically a long, dark gown and a simple headdress.', imageUrl: 'https://picsum.photos/seed/nhosi/200' },
  { id: 'hoa_people_cheongsam', name: 'Người Hoa (Xường Xám)', prompt: 'A beautiful Cheongsam (Xường Xám) as worn by the Hoa people in Vietnam, a form-fitting dress with a high collar and side slits.', imageUrl: 'https://picsum.photos/seed/cheongsam/200' },
  { id: 'lao_cai_ha_nhi', name: 'Dân Tộc Hà Nhì', prompt: 'The traditional costume of the Hà Nhì people from Lào Cai, characterized by a unique indigo headdress decorated with colorful beads and tassels.', imageUrl: 'https://picsum.photos/seed/hanhi/200' },
  { id: 'khmer_krom_outfit', name: 'Người Khmer Krom', prompt: 'The vibrant and colorful traditional clothing of the Khmer Krom people of the Mekong Delta, similar to Cambodian attire with rich silk sampot skirts.', imageUrl: 'https://picsum.photos/seed/khmerkrom/200' },
  { id: 'bac_ninh_quan_ho', name: 'Liền Anh Liền Chị', prompt: 'The elegant attire of Quan Họ folk singers from Bắc Ninh, featuring layered dresses, large flat hats (nón quai thao), and graceful scarves.', imageUrl: 'https://picsum.photos/seed/quanho/200' },
  { id: 'tay_people_indigo', name: 'Dân Tộc Tày', prompt: 'The traditional costume of the Tày people, made from hand-dyed indigo cotton, often with a simple design and a distinctive square black headscarf.', imageUrl: 'https://picsum.photos/seed/taypeople/200' },
  { id: 'ancient_hanoi_trader', name: 'Thương Nhân Hà Nội Xưa', prompt: 'The clothing of a trader in old Hanoi, a practical yet classic outfit suitable for life in the 36 streets.', imageUrl: 'https://picsum.photos/seed/hanoitrader/200' },
  { id: 'water_puppet_performer', name: 'Nghệ Nhân Rối Nước', prompt: 'The simple, rustic outfit of a water puppet performer, typically hidden behind a screen during a show.', imageUrl: 'https://picsum.photos/seed/waterpuppeteer/200' },
  { id: 'ly_son_fisherman', name: 'Ngư Dân Lý Sơn', prompt: 'The weathered, practical clothing of a fisherman from Lý Sơn island, adapted to a life at sea.', imageUrl: 'https://picsum.photos/seed/lyson/200' },
];

export const STYLES: Style[] = [
    { id: 'photorealistic', name: 'Chân Thực', prompt: 'A highly detailed, photorealistic style that looks like a real photograph taken with a professional DSLR camera.' },
    { id: 'cinematic', name: 'Điện Ảnh', prompt: 'A cinematic style with dramatic lighting, rich colors, and a wide aspect ratio feel, like a still from a movie.' },
    { id: 'fantasy_art', name: 'Vẽ Kỳ Ảo', prompt: 'A beautiful fantasy art style, with soft, glowing light, magical elements, and a dreamy, ethereal atmosphere.' },
    { id: 'oil_painting', name: 'Tranh Sơn Dầu', prompt: 'The style of a classic, luxurious oil painting, with visible brushstrokes, rich textures, and deep, vibrant colors.' },
    { id: 'watercolor', name: 'Tranh Màu Nước', prompt: 'A delicate and artistic watercolor painting style, with soft washes of color, light lines, and a whimsical feel.' },
    { id: 'studio_portrait', name: 'Ảnh Studio', prompt: 'A clean, professional studio portrait style with perfect lighting that highlights the subject, a slightly blurred background (bokeh), and a focus on capturing personality.' },
    { id: '3d_cartoon', name: 'Hoạt Hình 3D', prompt: 'The charming and polished style of a 3D animated movie, like those from Pixar or Disney, with soft lighting, detailed textures, and endearing character design.' },
    { id: 'anime', name: 'Anime Nhật Bản', prompt: 'A vibrant and expressive Japanese anime art style, with large, sparkling eyes, cel-shaded colors, and dynamic lines.' },
    { id: 'pencil_sketch', name: 'Phác Thảo Chì', prompt: 'A beautiful and timeless black and white pencil sketch style, with detailed shading, fine lines, and the texture of hand-drawn art on paper.' },
    { id: 'pop_art', name: 'Nghệ Thuật Pop Art', prompt: 'A bold and colorful Pop Art style inspired by Andy Warhol, using vibrant, contrasting colors, repeating patterns, and a graphic, comic-book-like feel.' }
];

export const SHOOTING_ANGLES: SimpleOption[] = [
    { id: 'eye_level', name: 'Góc Ngang Tầm Mắt', prompt: 'The photo is taken from an eye-level angle, creating a natural and direct connection with the subject.' },
    { id: 'low_angle', name: 'Góc Thấp (Hất Lên)', prompt: 'The photo is shot from a low angle, looking up at the subject, making them appear more heroic, grand, and powerful.' },
    { id: 'high_angle', name: 'Góc Cao (Nhìn Xuống)', prompt: 'The photo is shot from a high angle, looking down on the subject, which can create a sense of vulnerability or give a great view of the surroundings.' },
    { id: 'dutch_angle', name: 'Góc Nghiêng (Dutch Angle)', prompt: 'The camera is tilted to one side, creating a Dutch angle, adding a sense of dynamism or disorientation to the scene.' },
    { id: 'close_up', name: 'Chụp Cận Cảnh Gương Mặt', prompt: 'A close-up shot, tightly framing the subject\'s face to emphasize their emotions and expressions.' },
    { id: 'extreme_close_up', name: 'Chụp Siêu Cận Cảnh', prompt: 'An extreme close-up shot, focusing on a specific facial feature like the eyes or lips to create intense emotion.' },
    { id: 'medium_shot', name: 'Chụp Trung Cảnh (Nửa Người)', prompt: 'A medium shot, capturing the subject from the waist up, balancing detail with the surrounding environment.' },
    { id: 'cowboy_shot', name: 'Chụp Kiểu Cowboy (Tới Đùi)', prompt: 'A cowboy shot, framing the subject from mid-thigh up, a style famously used in Westerns.' },
    { id: 'full_shot', name: 'Chụp Toàn Thân', prompt: 'A full shot, capturing the subject from head to toe, showing their entire posture and attire.' },
    { id: 'wide_shot', name: 'Chụp Toàn Cảnh Rộng', prompt: 'A wide shot that captures the subject within their expansive environment, emphasizing the scale and atmosphere of the location.' },
    { id: 'worms_eye_view', name: 'Góc Nhìn Từ Dưới Đất', prompt: 'An extreme low angle, shot from ground level looking straight up, making the subject seem overwhelmingly tall and dominant.' },
    { id: 'birds_eye_view', name: 'Góc Nhìn Từ Trên Cao', prompt: 'A bird\'s-eye view, shot from directly overhead, providing an aerial perspective and a unique, map-like quality.' },
    { id: 'over_the_shoulder', name: 'Góc Chụp Qua Vai', prompt: 'Shot from behind a person, looking over their shoulder at the subject, creating a sense of intimacy and perspective.' },
    { id: 'pov', name: 'Góc Nhìn Chủ Quan (POV)', prompt: 'A point-of-view shot, showing the scene from the subject\'s own perspective, as if the viewer is seeing through their eyes.' },
    { id: 'profile_shot', name: 'Góc Chụp Nhìn Nghiêng', prompt: 'A profile shot, capturing the subject from the side, emphasizing their silhouette and facial features in a non-confrontational way.' },
    { id: 'three_quarter_view', name: 'Góc Chụp 3/4', prompt: 'A three-quarter view, where the subject is turned slightly away from the camera, offering more depth and dimension than a direct frontal shot.' },
    { id: 'telephoto_lens', name: 'Chụp Bằng Ống Kính Tele', prompt: 'The image is shot with a telephoto lens, creating a compressed perspective and a very shallow depth of field.' },
    { id: 'wide_angle_lens', name: 'Chụp Bằng Ống Kính Góc Rộng', prompt: 'The image is shot with a wide-angle lens, exaggerating depth and making the scene feel vast and immersive.' },
    { id: 'drone_shot', name: 'Góc Chụp Flycam', prompt: 'A high, sweeping drone shot from a distance, capturing the landscape and the subject\'s place within it.' },
    { id: 'selfie_angle', name: 'Góc Chụp Kiểu Selfie', prompt: 'The image is framed from a high, close angle, typical of a selfie, creating a casual and personal feel.' }
];

export const IMAGE_EFFECTS: SimpleOption[] = [
    { id: 'bokeh', name: 'Hiệu Ứng Xóa Phông (Bokeh)', prompt: 'The image has a beautiful, creamy bokeh effect, with the background artistically blurred into soft, out-of-focus highlights.' },
    { id: 'lens_flare', name: 'Hiệu Ứng Lóa Sáng (Lens Flare)', prompt: 'A cinematic lens flare is visible, with streaks of light from a bright source adding a touch of drama and magic.' },
    { id: 'golden_hour', name: 'Ánh Sáng Giờ Vàng', prompt: 'The photo is bathed in the warm, soft, and magical light of the golden hour, just after sunrise or before sunset.' },
    { id: 'blue_hour', name: 'Ánh Sáng Giờ Xanh', prompt: 'The photo is captured during the blue hour, with a deep, serene blue light and a tranquil, moody atmosphere.' },
    { id: 'high_contrast_bw', name: 'Trắng Đen Tương Phản Cao', prompt: 'A timeless and dramatic high-contrast black and white effect, with deep blacks and bright whites, focusing on form and texture.' },
    { id: 'vintage_sepia', name: 'Hiệu Ứng Cổ Điển (Sepia)', prompt: 'The image has a vintage, sepia tone effect, giving it a nostalgic, warm, and old-fashioned feel, like an old photograph.' },
    { id: 'film_grain', name: 'Hiệu Ứng Hạt Phim', prompt: 'The image has a subtle film grain texture, adding a nostalgic, cinematic, and analog feel.' },
    { id: 'vignette', name: 'Hiệu Ứng Tối Góc', prompt: 'A soft, dark vignette frames the subject, gently darkening the corners of the image to draw the viewer\'s eye to the center.' },
    { id: 'low_key_lighting', name: 'Ánh Sáng Tối (Low Key)', prompt: 'The scene is lit with low-key lighting, creating a dramatic, mysterious mood with dark shadows and selective highlights (chiaroscuro).' },
    { id: 'high_key_lighting', name: 'Ánh Sáng Sáng (High Key)', prompt: 'The scene is lit with high-key lighting, creating a bright, airy, and optimistic mood with minimal shadows.' },
    { id: 'soft_focus', name: 'Hiệu Ứng Mềm Mại, Mơ Màng', prompt: 'The image has a soft focus or dreamy glow effect, giving it a gentle, ethereal, and romantic quality.' },
    { id: 'motion_blur', name: 'Hiệu Ứng Chuyển Động Mờ', prompt: 'The background has a motion blur effect, suggesting speed and action, while the subject remains relatively sharp.' },
    { id: 'long_exposure', name: 'Hiệu Ứng Phơi Sáng Lâu', prompt: 'The image is created with a long exposure technique, blurring moving elements like water or clouds into smooth, ethereal textures.' },
    { id: 'double_exposure', name: 'Hiệu Ứng Chồng Ảnh', prompt: 'The image uses a double exposure effect, artistically blending the portrait with another image, like a landscape or a texture.' },
    { id: 'neon_cyberpunk', name: 'Ánh Sáng Neon (Cyberpunk)', prompt: 'The scene is illuminated by vibrant, futuristic neon lights, creating a cyberpunk aesthetic with saturated blues, pinks, and purples.' },
    { id: 'sunbeams', name: 'Hiệu Ứng Tia Nắng', prompt: 'Visible sunbeams or "god rays" stream through the scene, adding a magical, divine, or serene feeling.' },
    { id: 'light_leaks', name: 'Hiệu Ứng Rò Rỉ Sáng', prompt: 'The image features vintage-style light leaks, with hazy streaks of red or orange light adding a nostalgic, analog camera feel.' },
    { id: 'split_toning', name: 'Tông Màu Điện Ảnh (Teal & Orange)', prompt: 'The image has a cinematic split toning effect, with teal hues in the shadows and orange tones in the highlights.' },
    { id: 'infrared_effect', name: 'Hiệu Ứng Hồng Ngoại', prompt: 'The image has a surreal infrared effect, where green foliage turns white or pink and skies become dark and dramatic.' },
    { id: 'rim_lighting', name: 'Ánh Sáng Viền Kịch Tính', prompt: 'The subject is outlined with a strong, dramatic rim light from behind, separating them from the background and creating a powerful silhouette.' }
];

export const ASPECT_RATIOS: { value: AspectRatio, label: string }[] = [
    { value: '1:1', label: 'Vuông' },
    { value: '4:3', label: 'Ngang' },
    { value: '16:9', label: 'Widescreen' },
    { value: '9:16', label: 'Dọc' },
];

export const NUM_IMAGES_OPTIONS: number[] = [1, 2, 3, 4];

export const RESOLUTION_OPTIONS: { value: Resolution, label: string, prompt: string }[] = [
    { value: 'standard', label: 'Tiêu Chuẩn', prompt: 'Create a standard quality, professional photograph.' },
    { value: 'hd', label: 'Chất Lượng Cao', prompt: 'Create a high resolution, professional photograph with sharp focus and rich detail.' },
    { value: 'ultra_hd', label: 'Siêu Nét (8K)', prompt: 'Create an ultra high resolution, 8K, professional photograph with sharp focus and luxurious, photorealistic detail.' }
];